### ISSUE TITLE
Gallery program previews do not parse or evaluate correctly

### ISSUE THREAD

**Issue by leahjia** [wordplaydev/wordplay#196]
## Expected behavior

Program launches successfully with all content loaded as designed.

## Actual behavior

Provide detailed steps that consistently reproduce the behavior, including any example code. If you can, make the steps as minimal as possible, finding the smallest possible set of steps that still produce the unexpected behavior.

1. Go to http://localhost:5173
2. Click on "Galleries"
3. See error
4. Click on any icon that isn't displayed properly (the ones in orange with '!')
5. See error within the individual functionality

## Screenshots
<img width="1723" alt="error-1" src="https://github.com/wordplaydev/wordplay/assets/99011487/750f9eb1-e3ca-4b22-8da7-d46d0f57df0c">
<img width="1719" alt="error-2" src="https://github.com/wordplaydev/wordplay/assets/99011487/2a677819-fb7a-4273-925b-f4c3e82cf810">

## Environment

What platform, OS, browser, and version are you using?
Desktop

- Branch: main
- OS: MacOS, Win10+
- Browser: Chrome, Safari, Firefox, Edge

**Comment by amyjko** [comment]
Thanks @leahjia! I'm unable to reproduce this on mac OS Chrome or Edge. A few clarifications:

* The notes above say you are able to reproduce this on both mac OS and Win10+ and Chrome, Safari, Firefox, and Edge? Is that accurate?
* Are you sure your main branch is up to date? `git pull` and restart your vite dev server and make sure.

If this is a real issue, and not just an out of date branch, I suspect it may have something to do with browser inconsistencies in tokenization, so knowing the exact version and browser would be helpful.

**Comment by leahjia** [comment]
> Thanks @leahjia! I'm unable to reproduce this on mac OS Chrome or Edge. A few clarifications:
> 
> * The notes above say you are able to reproduce this on both mac OS and Win10+ and Chrome, Safari, Firefox, and Edge? Is that accurate?
> * Are you sure your main branch is up to date? `git pull` and restart your vite dev server and make sure.
> 
> If this is a real issue, and not just an out of date branch, I suspect it may have something to do with browser inconsistencies in tokenization, so knowing the exact version and browser would be helpful.

Hello @amyjko, 
- Yes the issue occurred on both Mac OS and Win10+ and the browsers listed.
- The issue occurred after updating with `git pull` and persisted after re-cloning the repo.
<img width="352" alt="image" src="https://github.com/wordplaydev/wordplay/assets/99011487/e97c5a5f-58c9-44b8-84e2-1d24585c155c">
<img width="210" alt="image" src="https://github.com/wordplaydev/wordplay/assets/99011487/7016e52a-43d9-47f2-904f-0073c4ff7fcc">
<img width="355" alt="image" src="https://github.com/wordplaydev/wordplay/assets/99011487/a7a13b1d-1986-4efe-8f57-c910d2a8505b">

**Comment by amyjko** [comment]
Thanks. I've assigned myself this one and will investigate after class today.

Two other things to help: 

* Can you visit [https://test.wordplay.dev](https://test.wordplay.dev) and see if it's happening there for you? It's not for me on any of these browsers, so that would help us determine if it's your machine, or possibly something about your local execution environment.

* What versions of your operating systems are you testing on? This can also impact things, since browsers rely on OS level APIs for some web standards.

**Comment by amyjko** [comment]
Update: I tried a fresh repo and install and cannot reproduce the issue on mac OS 14.0 on Chrome 117.0.5938.149, Safari 17, or Edge 117.0.2045.55. Can you please respond to the two bullets above?

**Comment by leahjia** [comment]
Hello @amyjko:
- https://test.wordplay.dev/ works well for me, so yes perhaps it has something to do with local environment.
- I am also using macOS 14.0

**Comment by amyjko** [comment]
And what browser versions? Those can matter as well.

**Comment by leahjia** [comment]
> <img alt="image" width="352" src="https://user-images.githubusercontent.com/99011487/274160274-e97c5a5f-58c9-44b8-84e2-1d24585c155c.png"> <img alt="image" width="210" src="https://user-images.githubusercontent.com/99011487/274160820-7016e52a-43d9-47f2-904f-0073c4ff7fcc.png"> <img alt="image" width="355" src="https://user-images.githubusercontent.com/99011487/274160740-a7a13b1d-1986-4efe-8f57-c910d2a8505b.png">

I've included browser versions in the previous comment. These are the ones I've tried on macOS. One other teammate have the issue on Firefox on Win10+ but I wasn't able to get their version.

**Comment by amyjko** [comment]
Ah, I missed the screen shots.

Have you checked the web inspector or console for any `vite` errors? That could give a hint as well.

**Comment by leahjia** [comment]
Here are the errors I received:
<img width="1359" alt="image" src="https://github.com/wordplaydev/wordplay/assets/99011487/7221d2f7-4061-46ae-9fb7-42e1f58676c4">
<img width="1352" alt="image" src="https://github.com/wordplaydev/wordplay/assets/99011487/cc31b9a0-3837-468f-8a34-607758fa79f2">

**Comment by amyjko** [comment]
Nothing promising there; that's what we'd expect if you're not running the firebase emulator locally. Hmmm.

Do you see this same issue if you create a project? Or is it just on the galleries page?

**Comment by leahjia** [comment]
I'm not sure what the expected behavior is for project page but here's what I see after creating a few random projects:
<img width="895" alt="Screenshot 2023-10-12 at 12 22 31 AM" src="https://github.com/wordplaydev/wordplay/assets/99011487/4eab49a8-099b-4a9a-b813-9bec6257a2df">

**Comment by amyjko** [comment]
Thanks! That all looks normal except for the exceptions on the two programs. It's suspicious that the cat program on the bottom left is working, but the other two aren't. A few more ideas for investigating:

* Can you drill in to that single project on the top and share it's exact code and the exception message that the program is evaluating to? There's a little "copy project as text" button on the bottom left of the project view that will copy it to the clipboard.

* Since you're seeing this across all browsers, it's likely not a browser-specific thing, but probably an operating system thing. What are the language settings in your operating systems? There could be some hidden Unicode language dependencies that are breaking how programs are parsed.

**Comment by leahjia** [comment]
I wasn't able to access the code and was taken to this error page:
<img width="1687" alt="image" src="https://github.com/wordplaydev/wordplay/assets/99011487/d237f39d-9d75-42c2-8b39-f7f1388cebf9">

I'm using English on my OS and no others.

**Comment by amyjko** [comment]
Leave full screen and you'll see the code. It's the second button from the right in the toolbar on the top left.

**Comment by leahjia** [comment]
I didn't type in much but here's what's in the project at the top

=== start
Phrase('🐈'Borel)

**Comment by amyjko** [comment]
That's a defective program. `Borel` refers to an undefined name, so the exception is valid. So that's not going to help us debug the gallery problems (which don't have defects in them). If you remove the undefined reference to `Borel`, is there still an exception?

**Comment by leahjia** [comment]
The exception is gone after removing `Borel`. If that's expected then projects page is working properly.

**Comment by amyjko** [comment]
Can you share some code from one of the gallery pages that isn't working, but should be?

**Comment by leahjia** [comment]
I figured out the issue - it has something to do with CRLF vs. LF line endings. The app runs into errors when the files are using CRLF line endings. Switching to LF resolved it. 
I changed the setting by running this command and cloned the project again. Now the Galleries page works properly.
```
git config --global core.autocrlf input
```

**Comment by amyjko** [comment]
Good catch! And that makes total sense; the parser only looks for line feeds (`\n`) not carriage returns, so all programs with a line break were failing. Let's not consider this issue closed though, since we clearly need to prevent this from happening on other installs on windows. I'll do some research on best practices for preventing this crossplatform issue.

**Comment by amyjko** [comment]
This should be resolved now; we needed to make a `.gitattributes` with a repository specific behavior for line endings (and for `.wp` files in particular, since the parser relies only on `LF`. Anyone seeing this issue should `git pull` to get the attributes and then run:

`git add --renormalize .`

This should resolve the issues.

**Comment by vTempo** [comment]
This seems to still be an issue for a lot of us even after the above instructions.

**Comment by leahjia** [comment]
> This seems to still be an issue for a lot of us even after the above instructions.

@vTempo Have you tried the approach I posted as well? Setting git config worked for me and another teammate.

**Comment by vTempo** [comment]
> > This seems to still be an issue for a lot of us even after the above instructions.
> 
> @vTempo Have you tried the approach I posted as well? Setting git config worked for me and another teammate.

I tried it earlier which didn't work, but I just tried re-cloning the repo and it seems to be fine for now.

I'll let my teammates who are still having this issue know about this as well.
